services:
  - type: web
    name: aivoice
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg pkg-config
      pip install -U pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
